//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace File.TestLogger {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("File.TestLogger.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to vstest.console.{0}_{1}_{2:yyyyMMdd_HHmmssfff}.log.
        /// </summary>
        internal static string DefaultLogFileName {
            get {
                return ResourceManager.GetString("DefaultLogFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Additional Information Messages:.
        /// </summary>
        internal static string Message_AdditionalInformationMessagesHeader {
            get {
                return ResourceManager.GetString("Message_AdditionalInformationMessagesHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debug Traces Messages:.
        /// </summary>
        internal static string Message_DebugTracesMessagesHeader {
            get {
                return ResourceManager.GetString("Message_DebugTracesMessagesHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0:N2} Days.
        /// </summary>
        internal static string Message_DurationLabelDays {
            get {
                return ResourceManager.GetString("Message_DurationLabelDays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0:N2} Hours.
        /// </summary>
        internal static string Message_DurationLabelHours {
            get {
                return ResourceManager.GetString("Message_DurationLabelHours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0:N2} Minutes.
        /// </summary>
        internal static string Message_DurationLabelMinutes {
            get {
                return ResourceManager.GetString("Message_DurationLabelMinutes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0:N2} Seconds.
        /// </summary>
        internal static string Message_DurationLabelSeconds {
            get {
                return ResourceManager.GetString("Message_DurationLabelSeconds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error Message:.
        /// </summary>
        internal static string Message_ErrorMesageHeader {
            get {
                return ResourceManager.GetString("Message_ErrorMesageHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log file: {0}.
        /// </summary>
        internal static string Message_LogFilePath {
            get {
                return ResourceManager.GetString("Message_LogFilePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stack Trace:.
        /// </summary>
        internal static string Message_StackTraceHeader {
            get {
                return ResourceManager.GetString("Message_StackTraceHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Standard Error Messages:.
        /// </summary>
        internal static string Message_StandardErrorMessagesHeader {
            get {
                return ResourceManager.GetString("Message_StandardErrorMessagesHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Standard Output Messages:.
        /// </summary>
        internal static string Message_StandardOutputMessagesHeader {
            get {
                return ResourceManager.GetString("Message_StandardOutputMessagesHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starting test execution, please wait....
        /// </summary>
        internal static string Message_StartingTestExecution {
            get {
                return ResourceManager.GetString("Message_StartingTestExecution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0:N2} h.
        /// </summary>
        internal static string Message_TestDurationLabelHours {
            get {
                return ResourceManager.GetString("Message_TestDurationLabelHours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0:N0} ms.
        /// </summary>
        internal static string Message_TestDurationLabelMilliseconds {
            get {
                return ResourceManager.GetString("Message_TestDurationLabelMilliseconds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0:N2} m.
        /// </summary>
        internal static string Message_TestDurationLabelMinutes {
            get {
                return ResourceManager.GetString("Message_TestDurationLabelMinutes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0:N2} s.
        /// </summary>
        internal static string Message_TestDurationLabelSeconds {
            get {
                return ResourceManager.GetString("Message_TestDurationLabelSeconds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}: {1}.
        /// </summary>
        internal static string Message_TestOutcome {
            get {
                return ResourceManager.GetString("Message_TestOutcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed.
        /// </summary>
        internal static string Message_TestOutcomeFailedLabel {
            get {
                return ResourceManager.GetString("Message_TestOutcomeFailedLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passed.
        /// </summary>
        internal static string Message_TestOutcomePassedLabel {
            get {
                return ResourceManager.GetString("Message_TestOutcomePassedLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skipped.
        /// </summary>
        internal static string Message_TestOutcomeSkippedLabel {
            get {
                return ResourceManager.GetString("Message_TestOutcomeSkippedLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test run aborted..
        /// </summary>
        internal static string Message_TestRunAborted {
            get {
                return ResourceManager.GetString("Message_TestRunAborted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test run aborted with error:.
        /// </summary>
        internal static string Message_TestRunAbortedWithError {
            get {
                return ResourceManager.GetString("Message_TestRunAbortedWithError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test run failed..
        /// </summary>
        internal static string Message_TestRunFailed {
            get {
                return ResourceManager.GetString("Message_TestRunFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to      Failed.
        /// </summary>
        internal static string Message_TestRunStasticsFailed {
            get {
                return ResourceManager.GetString("Message_TestRunStasticsFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to      Passed.
        /// </summary>
        internal static string Message_TestRunStatisticsPassed {
            get {
                return ResourceManager.GetString("Message_TestRunStatisticsPassed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to     Skipped.
        /// </summary>
        internal static string Message_TestRunStatisticsSkipped {
            get {
                return ResourceManager.GetString("Message_TestRunStatisticsSkipped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test run successful..
        /// </summary>
        internal static string Message_TestRunSuccessful {
            get {
                return ResourceManager.GetString("Message_TestRunSuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A total of {0} test files matched the specified pattern..
        /// </summary>
        internal static string Message_TestSourcesToRun {
            get {
                return ResourceManager.GetString("Message_TestSourcesToRun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duration: .
        /// </summary>
        internal static string Message_TestSourceSummaryDurationLabel {
            get {
                return ResourceManager.GetString("Message_TestSourceSummaryDurationLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed: {0}, .
        /// </summary>
        internal static string Message_TestSourceSummaryFailedCountLabel {
            get {
                return ResourceManager.GetString("Message_TestSourceSummaryFailedCountLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed! .
        /// </summary>
        internal static string Message_TestSourceSummaryFailedLabel {
            get {
                return ResourceManager.GetString("Message_TestSourceSummaryFailedLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passed: {0}, .
        /// </summary>
        internal static string Message_TestSourceSummaryPassedCountLabel {
            get {
                return ResourceManager.GetString("Message_TestSourceSummaryPassedCountLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passed! .
        /// </summary>
        internal static string Message_TestSourceSummaryPassedLabel {
            get {
                return ResourceManager.GetString("Message_TestSourceSummaryPassedLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skipped: {0}, .
        /// </summary>
        internal static string Message_TestSourceSummarySkippedCountLabel {
            get {
                return ResourceManager.GetString("Message_TestSourceSummarySkippedCountLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skipped!.
        /// </summary>
        internal static string Message_TestSourceSummarySkippedLabel {
            get {
                return ResourceManager.GetString("Message_TestSourceSummarySkippedLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total: {0}, .
        /// </summary>
        internal static string Message_TestSourceSummaryTotalCountLabel {
            get {
                return ResourceManager.GetString("Message_TestSourceSummaryTotalCountLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total tests: .
        /// </summary>
        internal static string Message_TotalTestsHeader {
            get {
                return ResourceManager.GetString("Message_TotalTestsHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Total time: .
        /// </summary>
        internal static string Message_TotalTimeHeader {
            get {
                return ResourceManager.GetString("Message_TotalTimeHeader", resourceCulture);
            }
        }
    }
}
