name: CI

on:
  workflow_dispatch:
  push:
    branches: 
      - main
      - rel/*
  pull_request:
    branches: 
      - main
      - rel/*

env:
  ArtifactsDirectoryName: 'artifacts'
  TestResultsDirectoryName: 'coverage'
  CommonTestArguments: '--no-restore --no-build --logger trx /noautorsp'
  BuildConfiguration: 'Debug'
  BuildPlatform: 'Any CPU'
  ContinuousIntegrationBuild: 'true'

jobs:
  BuildAndTest:
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]
        include:
          - os: windows-latest
            name: Windows
          - os: ubuntu-latest
            name: Linux
          - os: macos-latest
            name: MacOS
      fail-fast: false

    name: Build and Test (${{ matrix.name }})
    runs-on: ${{ matrix.os }}
  
    steps:
    - name: Checkout
      uses: actions/checkout@v5
      with:
        fetch-depth: 0

    - name: Install .NET 8.x
      uses: actions/setup-dotnet@v5
      with:
        dotnet-version: | 
          8.x
          9.x

    - name: Build Solution
      run: dotnet build "/Property:Platform=${{ env.BuildPlatform }};Configuration=${{ env.BuildConfiguration }}" "/BinaryLogger:${{ env.ArtifactsDirectoryName }}/build.binlog"

    - name: Run Unit Tests (.NET Framework)
      if: ${{ matrix.name == 'Windows' }}
      run: dotnet test ${{ env.CommonTestArguments }} --framework net472 "/Property:Platform=${{ env.BuildPlatform }};Configuration=${{ env.BuildConfiguration }}" "/BinaryLogger:${{ env.ArtifactsDirectoryName }}/test-net472.binlog"

    - name: Run Unit Tests (.NET 8.0)
      run: dotnet test ${{ env.CommonTestArguments }} --framework net8.0 "/Property:Platform=${{ env.BuildPlatform }};Configuration=${{ env.BuildConfiguration }}" "/BinaryLogger:${{ env.ArtifactsDirectoryName }}/test-net8.0.binlog"

    - name: Upload Test Results
      uses: actions/upload-artifact@v5
      if: success() || failure()
      with:
        name: test-results-${{ matrix.name }}
        path: '**/TestResults/*.trx'
        if-no-files-found: error

    - name: Upload Artifacts
      uses: actions/upload-artifact@v5
      if: success() || failure()
      with:
        name: ${{ env.ArtifactsDirectoryName }}-${{ matrix.name }}
        path: ${{ env.ArtifactsDirectoryName }}